#!/bin/sh

exec docker run --rm -ti \
                -e OS_USERNAME=$OS_USERNAME \
                -e OS_PASSWORD=$OS_PASSWORD \
                -e OS_TENANT_NAME=$OS_TENANT_NAME \
                -e OS_AUTH_URL=$OS_AUTH_URL \
                -v $HOME/.ssh/id_rsa.pub:/home/openshift-ansible/.ssh/id_rsa.pub:ro \
                -v $SSH_AUTH_SOCK:/tmp/ssh/agent \
                -e SSH_AUTH_SOCK=/tmp/ssh/agent \
                lhuard1a/openshift-ansible:2015.05.18 "$@"
